<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHTuSI3Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHTuSI3Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHTuSI3Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHTuSI3Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHTuSI3Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'HTuSI3Y',
    'container.build_id' => 'e19d5b65',
    'container.build_time' => 1598208730,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHTuSI3Y');
